# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-30 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Distincion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_distincion', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('entidad', models.CharField(max_length=50)),
                ('ambito', models.CharField(max_length=1)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('usuario_registro', models.CharField(max_length=20)),
                ('fecha_autenticacion', models.DateField(null=True)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('cod_docente', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=1)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('usuario_registro', models.CharField(max_length=10)),
                ('fecha_activacion', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docente_Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=1)),
                ('lectura', models.CharField(max_length=1)),
                ('escritura', models.CharField(max_length=1)),
                ('conversacion', models.CharField(max_length=1)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('usuario_registro', models.CharField(max_length=20)),
                ('fecha_autenticacion', models.DateField(null=True)),
                ('estado', models.CharField(max_length=1)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo_vitae.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Civil',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_obtenido', models.CharField(max_length=50)),
                ('semestres', models.CharField(max_length=2)),
                ('fecha_inicio', models.DateField()),
                ('fecha_titulo', models.DateField()),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('usuario_registro', models.CharField(max_length=20)),
                ('fecha_autenticacion', models.DateField(null=True)),
                ('estado', models.CharField(max_length=1)),
                ('cod_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo_vitae.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('direccion', models.CharField(max_length=500)),
                ('lugar', models.CharField(max_length=5)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('usuario_registro', models.CharField(max_length=20)),
                ('fecha_autenticacion', models.DateField(null=True)),
                ('estado', models.CharField(max_length=1)),
                ('cod_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo_vitae.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cargo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=500)),
                ('telefono', models.CharField(max_length=10)),
                ('funciones', models.CharField(max_length=500)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('usuario_registro', models.CharField(max_length=20)),
                ('fecha_autenticacion', models.DateField(null=True)),
                ('estado', models.CharField(max_length=1)),
                ('lugar', models.CharField(max_length=5)),
                ('cod_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo_vitae.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='Formacion_Continua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intencidad', models.CharField(max_length=2)),
                ('fecha_inicio', models.DateField()),
                ('fecha_terminacion', models.DateField()),
                ('fecha_titulo', models.DateField()),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('usuario_registro', models.CharField(max_length=20)),
                ('fecha_autenticacion', models.DateField(null=True)),
                ('estado', models.CharField(max_length=1)),
                ('cod_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo_vitae.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Investigacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('usuario_registro', models.CharField(max_length=20)),
                ('fecha_autenticacion', models.DateField(null=True)),
                ('estado', models.CharField(max_length=1)),
                ('cod_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo_vitae.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('id_dpto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo_vitae.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=20)),
                ('nombre2', models.CharField(max_length=20, null=True)),
                ('apellido1', models.CharField(max_length=20)),
                ('apellido2', models.CharField(max_length=20, null=True)),
                ('tarjeta_profesional', models.CharField(max_length=15)),
                ('sexo', models.CharField(max_length=1)),
                ('fecha_nac', models.DateField()),
                ('hijos', models.IntegerField()),
                ('telefono1', models.CharField(max_length=10)),
                ('telefono2', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=500)),
                ('correo_inst', models.EmailField(max_length=30)),
                ('correo_oper', models.EmailField(max_length=30)),
                ('twitter', models.CharField(max_length=30)),
                ('facebook', models.CharField(max_length=30)),
                ('sitioweb', models.CharField(max_length=30)),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo_vitae.Estado_Civil')),
                ('municipio_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipio_exp', to='curriculo_vitae.Municipio')),
                ('municipio_nac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipio_nac', to='curriculo_vitae.Municipio')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo_vitae.Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('divulgacion', models.CharField(max_length=30)),
                ('sitio_web', models.CharField(max_length=50)),
                ('revista', models.CharField(max_length=50)),
                ('periodico', models.CharField(max_length=50)),
                ('volumen', models.IntegerField()),
                ('editorial', models.CharField(max_length=30)),
                ('isbn', models.CharField(max_length=20)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('usuario_registro', models.CharField(max_length=20)),
                ('fecha_autenticacion', models.DateField(null=True)),
                ('estado', models.CharField(max_length=1)),
                ('descripcion', models.TextField(max_length=500)),
                ('cod_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo_vitae.Docente')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo_vitae.Idioma')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Continua',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Documento',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Evento',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Formacion',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Investigacion',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Participacion',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Publicacion',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='publicacion',
            name='tipo_publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo_vitae.Tipo_Publicacion'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo_vitae.Tipo_Documento'),
        ),
        migrations.AddField(
            model_name='investigacion',
            name='tipo_investigacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo_vitae.Tipo_Investigacion'),
        ),
        migrations.AddField(
            model_name='formacion_continua',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo_vitae.Institucion'),
        ),
        migrations.AddField(
            model_name='formacion_continua',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo_vitae.Municipio'),
        ),
        migrations.AddField(
            model_name='formacion_continua',
            name='tipo_continua',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo_vitae.Tipo_Continua'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo_vitae.Tipo_Evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_parcipacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo_vitae.Tipo_Participacion'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo_vitae.Institucion'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo_vitae.Municipio'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='tipo_formacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo_vitae.Tipo_Formacion'),
        ),
        migrations.AddField(
            model_name='docente_idioma',
            name='idioma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo_vitae.Idioma'),
        ),
        migrations.AddField(
            model_name='docente',
            name='cedula',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='curriculo_vitae.Persona'),
        ),
        migrations.AddField(
            model_name='distincion',
            name='cod_docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo_vitae.Docente'),
        ),
        migrations.AddField(
            model_name='distincion',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo_vitae.Municipio'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='id_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo_vitae.Pais'),
        ),
        migrations.AlterUniqueTogether(
            name='docente_idioma',
            unique_together=set([('docente', 'idioma')]),
        ),
    ]
